package com.lambdaschool.javaordersapp.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "orders")
public class Order
{
    // Generate a unique primary key
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO) // standard
    // -------------- Table Fields ------------
    private long ordnum; // primary key

    private double ordamount;
    private double advanceamount;
    private String orderdescription;

    // ----------- Association Fields ---------

    // This creates a joining table between the Order Table and the Payment Table
    @ManyToMany()
    @JoinTable(name = "orderpayments",
                        joinColumns = @JoinColumn(name = "ordnum"), //this is the string needs to be the name of the primary key
                        inverseJoinColumns = @JoinColumn(name = "paymentid"))
    @JsonIgnoreProperties("orders") // Why are we doing this?
    Set<Payment> payments = new HashSet<>(); // What is this for? // hashSet is a key value data type where the keys are generated by the computer.

    // This connects the Order Table to the Customer Table
    @ManyToOne()
    @JoinColumn(name = "custcode", nullable = false)
    private Customer customers; // what is this ?

    // ------------ Constructors -------------
    public Order()
    {
        // default constructor for JPA
    }

    // Constructor with parameters
    public Order(
        double ordamount,
        double advanceamount,
        String orderdescription,
        Customer customers)
    {
        this.ordamount = ordamount;
        this.advanceamount = advanceamount;
        this.orderdescription = orderdescription;
        this.payments = payments;
        this.customers = customers;
    }

    // ---------- Getters and Setters ---------

    public long getOrdnum()
    {
        return ordnum;
    }

    public void setOrdnum(long ordnum)
    {
        this.ordnum = ordnum;
    }

    public double getOrdamount()
    {
        return ordamount;
    }

    public void setOrdamount(double ordamount)
    {
        this.ordamount = ordamount;
    }

    public double getAdvanceamount()
    {
        return advanceamount;
    }

    public void setAdvanceamount(double advanceamount)
    {
        this.advanceamount = advanceamount;
    }

    public String getOrderdescription()
    {
        return orderdescription;
    }

    public void setOrderdescription(String orderdescription)
    {
        this.orderdescription = orderdescription;
    }

    public Set<Payment> getPayments()
    {
        return payments;
    }

    public void setPayments(Set<Payment> payments)
    {
        this.payments = payments;
    }

    public Customer getCustomers()
    {
        return customers;
    }

    public void setCustomers(Customer customers)
    {
        this.customers = customers;
    }
}
